services:
  - type: web
    name: apitaphoavip
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app -b 0.0.0.0:$PORT"
    envVars:
      - key: ADMIN_SECRET
        value: adminlinhdz
      - key: DB_PATH
        value: store_profiles.db
      - key: REQ_TIMEOUT
        value: "2"
      - key: DEBUG_ERRORS
        value: "0"
